services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: xcsm_front
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - xcsm_network

networks:
  xcsm_network:
    driver: bridge
